### ISSUE TITLE
image_url not support .gif images

### ISSUE THREAD

**Issue by ervilis** [opps/opps#468]
image_url is not supporting images .gif but thumbor supports.

See...

https://github.com/thumbor/thumbor/pull/321

http://thumbor.thumborize.me/unsafe/250x175/https://raw.githubusercontent.com/thumbor/thumbor/93ded95513ada3e95585a1c51a19a1db68c306d6/60a48000-0198-11e4-978c-f1a9f360fa11.gif

https://raw.githubusercontent.com/thumbor/thumbor/93ded95513ada3e95585a1c51a19a1db68c306d6/60a48000-0198-11e4-978c-f1a9f360fa11.gif

**Comment by avelino** [comment]
Fixed man! Sorry delay on merge PR...
