### ISSUE TITLE
Filter by site - Articles

### ISSUE THREAD

**Issue by henriquechehad** [opps/opps#472]
The list view of Articles (Post, Links, etc) doesn't show a filter by site option
![article filters](https://cloud.githubusercontent.com/assets/1929407/7183764/b278e5cc-e42f-11e4-8522-00494848ce2d.png)

**Comment by henriquechehad** [comment]
Added the feature in this fork: 

https://github.com/campusparty/opps/tree/henriquechehad/added-site-filter-to-publisheradmin

**Comment by avelino** [comment]
very good, send PR pls
