### ISSUE TITLE
ContainerBox unique fields validation

### ISSUE THREAD

**Issue by henriquechehad** [opps/opps#474]
On saving a containerbox if exists another with same site, slug, long_slug (unique together fields) shows a error.

Example:

IntegrityError: duplicate key value violates unique constraint "containers_containerbox_site_id_3e4fcd59a96989ef_uniq"
DETAIL:  Key (site_id, channel_long_slug, slug)=(4, example, example) already exists.

Fix:
https://github.com/campusparty/opps/commit/0d1db4e5f2427cba7773985d24d17fd18046a347

Send PR?

**Comment by avelino** [comment]
Very very good, can you write a code to validate the implementation?

**Comment by henriquechehad** [comment]
Thank you! Implementation of tests ?

**Comment by avelino** [comment]
Yep

**Comment by henriquechehad** [comment]
Here is the branch:
https://github.com/campusparty/opps/commits/henriquechehad/prevent-repeated-containerbox

Commit:
https://github.com/campusparty/opps/commit/9d8626ee05b0e8beeb132cf95f17c728ab93b6a7

I renamed the test file after, in this commit.
https://github.com/campusparty/opps/commit/15f5e8208c28d89fcbfd2adf249a621aad06903a


Please can you check if this test is ok?
