### ISSUE TITLE
Channels: Home Page / Site

### ISSUE THREAD

**Issue by henriquechehad** [opps/opps#475]
When enable the Channel as Home Page of a site, the validation is checking if the current site have home page, instead of the selected site in the form.

Example:
The http://site01.com have a home page.

But when I access http://site01.com/admin/ and try to add a channel as homepage to http://site02.com shows the error bellow:

![channel_homepage](https://cloud.githubusercontent.com/assets/1929407/7204414/4ff75b76-e4f8-11e4-9c5e-2216f5049a87.png)

**Comment by henriquechehad** [comment]
Branch:
https://github.com/campusparty/opps/tree/henriquechehad/fix-homepage-validation


Send PR?

**Comment by avelino** [comment]
yep send! thanks
